//! patch-core — OSC transport, discovery, reliability, channel state.
//!
//! Linked into the Flutter app as a `cdylib`/`staticlib` via
//! `flutter_rust_bridge` (see `Cargo.toml` `[lib] crate-type` and
//! `patch_app/rust_builder/`). All Dart-callable functions live in
//! `crate::api`; the rest of the crate is internal.

pub mod discovery;
pub mod osc;
pub mod reliability;
pub mod state;
pub mod transport;

pub mod api;

// Generated by `flutter_rust_bridge_codegen`. Provides the FFI glue + the
// `StreamSink` type used by `api::subscribe_events`. Regenerated whenever
// `api.rs` changes.
mod frb_generated;
