// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A logical communication channel.
class Channel {
  /// Stable slug used in OSC addresses (e.g. "rf", "foh").
  final String id;

  /// Human-readable display name shown in the UI.
  final String displayName;

  /// Hex colour for UI differentiation (e.g. "#E53935").
  final String color;

  /// Pre-configured macro messages for this channel.
  final List<MacroMessage> macros;

  /// Flash this channel's message box when a critical (priority 3) message arrives.
  final bool flashOnCritical;

  /// Flash this channel's message box on every incoming message.
  final bool flashOnMessage;

  /// Per-channel flash pulse count override. None = use global setting.
  final int? flashCount;

  const Channel({
    required this.id,
    required this.displayName,
    required this.color,
    required this.macros,
    required this.flashOnCritical,
    required this.flashOnMessage,
    this.flashCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      color.hashCode ^
      macros.hashCode ^
      flashOnCritical.hashCode ^
      flashOnMessage.hashCode ^
      flashCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Channel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          color == other.color &&
          macros == other.macros &&
          flashOnCritical == other.flashOnCritical &&
          flashOnMessage == other.flashOnMessage &&
          flashCount == other.flashCount;
}

/// A one-tap/keyboard macro message.
class MacroMessage {
  /// Short label shown on the button (e.g. "HOLD", "CLEAR", "BACK IN 5").
  final String label;

  /// The message text that will be sent.
  final String payload;

  /// Optional key binding (e.g. "F1", "ctrl+1").
  final String? keyBinding;

  /// Priority override — defaults to Info.
  final int priority;

  const MacroMessage({
    required this.label,
    required this.payload,
    this.keyBinding,
    required this.priority,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      payload.hashCode ^
      keyBinding.hashCode ^
      priority.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacroMessage &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          payload == other.payload &&
          keyBinding == other.keyBinding &&
          priority == other.priority;
}
