// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A logical communication channel.
class Channel {
  /// Stable slug used in OSC addresses (e.g. "rf", "foh").
  final String id;

  /// Human-readable display name shown in the UI.
  final String displayName;

  /// Hex colour for UI differentiation (e.g. "#E53935").
  final String color;

  /// Pre-configured macro messages for this channel.
  final List<MacroMessage> macros;

  /// Flash this channel's message box when a critical (priority 3) message arrives.
  final bool flashOnCritical;

  /// Flash this channel's message box on every incoming message.
  final bool flashOnMessage;

  /// Per-channel flash pulse count override. None = use global setting.
  final int? flashCount;

  const Channel({
    required this.id,
    required this.displayName,
    required this.color,
    required this.macros,
    required this.flashOnCritical,
    required this.flashOnMessage,
    this.flashCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      color.hashCode ^
      macros.hashCode ^
      flashOnCritical.hashCode ^
      flashOnMessage.hashCode ^
      flashCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Channel &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          color == other.color &&
          macros == other.macros &&
          flashOnCritical == other.flashOnCritical &&
          flashOnMessage == other.flashOnMessage &&
          flashCount == other.flashCount;
}

/// A one-tap/keyboard macro message.
class MacroMessage {
  /// Short label shown on the button (e.g. "HOLD", "CLEAR", "BACK IN 5").
  final String label;

  /// The message text that will be sent.
  final String payload;

  /// Optional key binding (e.g. "F1", "ctrl+1").
  final String? keyBinding;

  /// Priority override — defaults to Info.
  final int priority;

  /// Optional MIDI Note number (0–127) that fires this macro. The engine's MIDI
  /// listener fires the macro on its own channel when a Note On for this number
  /// arrives (per-channel macros only).
  final int? midiNote;

  /// Optional MIDI Control Change number (0–127) that fires this macro (on a CC
  /// value ≥ 64, i.e. a footswitch "press").
  final int? midiCc;

  /// Optional outbound OSC target — when the macro fires, Patch *also* sends this
  /// OSC message to external gear, alongside the normal Patch channel message.
  final OscTarget? osc;

  const MacroMessage({
    required this.label,
    required this.payload,
    this.keyBinding,
    required this.priority,
    this.midiNote,
    this.midiCc,
    this.osc,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      payload.hashCode ^
      keyBinding.hashCode ^
      priority.hashCode ^
      midiNote.hashCode ^
      midiCc.hashCode ^
      osc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MacroMessage &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          payload == other.payload &&
          keyBinding == other.keyBinding &&
          priority == other.priority &&
          midiNote == other.midiNote &&
          midiCc == other.midiCc &&
          osc == other.osc;
}

/// An outbound OSC target attached to a macro (dual action — fired alongside the
/// Patch message). Lets a macro trigger QLab cues, Companion buttons, vMix
/// overlays, etc. from the same button/key/MIDI that messages the crew.
class OscTarget {
  /// Destination IP address (e.g. "192.168.1.50").
  final String address;

  /// Destination UDP port (e.g. 53000 for QLab).
  final int port;

  /// OSC address path, must start with '/' (e.g. "/cue/1/start").
  final String path;

  /// Optional single argument, stored as text regardless of `arg_type` —
  /// parsed into the matching `OscType` (Int/Float/String) when the macro
  /// fires (`osc::codec::build_osc_arg`).
  final String? arg;

  /// How `arg` should be parsed/sent. Defaults to `String` so existing
  /// macros and hand-edited `patch.toml` files without this field keep
  /// behaving exactly as before this field was added.
  final OscArgKind argType;

  const OscTarget({
    required this.address,
    required this.port,
    required this.path,
    this.arg,
    required this.argType,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      port.hashCode ^
      path.hashCode ^
      arg.hashCode ^
      argType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OscTarget &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          path == other.path &&
          arg == other.arg &&
          argType == other.argType;
}
