// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class StaticPeer {
  final String address;
  final int port;
  final String? label;

  const StaticPeer({required this.address, required this.port, this.label});

  @override
  int get hashCode => address.hashCode ^ port.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StaticPeer &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          port == other.port &&
          label == other.label;
}
