// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

enum DiscoveryMode { mdns, oscBeacon, manualIp }

/// A discovered or manually-added peer on the network.
class Peer {
  final UuidValue peerId;
  final String peerName;

  /// Channels this peer is currently subscribed to.
  final List<String> channels;

  /// How we found this peer.
  final DiscoveryMode discoveryMode;

  /// IP address (v4 or v6).
  final String address;

  /// OSC UDP port.
  final int oscPort;
  final DateTime lastSeen;

  const Peer({
    required this.peerId,
    required this.peerName,
    required this.channels,
    required this.discoveryMode,
    required this.address,
    required this.oscPort,
    required this.lastSeen,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      peerName.hashCode ^
      channels.hashCode ^
      discoveryMode.hashCode ^
      address.hashCode ^
      oscPort.hashCode ^
      lastSeen.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Peer &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          channels == other.channels &&
          discoveryMode == other.discoveryMode &&
          address == other.address &&
          oscPort == other.oscPort &&
          lastSeen == other.lastSeen;
}
