// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SessionMeta {
  final String slug;
  final String name;
  final DateTime createdAt;
  final BigInt channelCount;

  const SessionMeta({
    required this.slug,
    required this.name,
    required this.createdAt,
    required this.channelCount,
  });

  @override
  int get hashCode =>
      slug.hashCode ^
      name.hashCode ^
      createdAt.hashCode ^
      channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionMeta &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name &&
          createdAt == other.createdAt &&
          channelCount == other.channelCount;
}
