// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// A flash/page event targeting a specific channel.
class ChannelFlash {
  final String channelId;
  final UuidValue senderId;
  final String senderName;

  const ChannelFlash({
    required this.channelId,
    required this.senderId,
    required this.senderName,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^ senderId.hashCode ^ senderName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelFlash &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          senderId == other.senderId &&
          senderName == other.senderName;
}

/// Type of a single outbound OSC macro argument — selects which `rosc::OscType`
/// variant the macro's stored `arg` string is parsed into when it fires.
/// Variant names mirror `rosc::OscType` exactly (`Int`/`Float`/`String`); only
/// the 32-bit `Int`/`Float` wire types are supported, not `Long`/`Double`, since
/// those are the OSC types most consoles/show-control gear expect.
///
/// Serialized as a plain string (`"Float"`, not an int code) — unlike
/// `Priority`, this never travels over the wire itself, it only selects how
/// `arg` gets encoded, so there's no compactness reason to int-code it.
enum OscArgKind { string, int, float }

/// A single PATCH message — maps 1-to-1 to the `/patch/message` OSC packet.
/// Flash log entries reuse this type with `is_flash: true` so they flow
/// through the same message buffer and bridge path as regular messages.
class PatchMessage {
  /// UUID v4 — unique per message, used for ACK and dedup.
  final UuidValue messageId;

  /// Stable UUID for the sender (persisted across sessions).
  final UuidValue senderId;

  /// Human-readable display name for the sender.
  final String senderName;

  /// Stable channel ID (slug, e.g. "rf", "foh").
  final String channelId;

  /// UTC timestamp when the message was created.
  final DateTime timestamp;
  final Priority priority;

  /// The actual message text or shortcut payload.
  final String payload;

  /// True for synthesized Flash log entries (never for wire messages).
  final bool isFlash;

  /// Display name of the peer that sent the Flash (Flash log entries only).
  final String? flashSenderName;

  /// Production role of the peer that sent the Flash (Flash log entries only).
  final String? flashSenderRole;

  const PatchMessage({
    required this.messageId,
    required this.senderId,
    required this.senderName,
    required this.channelId,
    required this.timestamp,
    required this.priority,
    required this.payload,
    required this.isFlash,
    this.flashSenderName,
    this.flashSenderRole,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      channelId.hashCode ^
      timestamp.hashCode ^
      priority.hashCode ^
      payload.hashCode ^
      isFlash.hashCode ^
      flashSenderName.hashCode ^
      flashSenderRole.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatchMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          channelId == other.channelId &&
          timestamp == other.timestamp &&
          priority == other.priority &&
          payload == other.payload &&
          isFlash == other.isFlash &&
          flashSenderName == other.flashSenderName &&
          flashSenderRole == other.flashSenderRole;
}

/// A presence/heartbeat announcement.
class PeerPresence {
  final UuidValue peerId;
  final String peerName;

  /// Which channels this peer is currently subscribed to.
  final List<String> channels;

  /// Optional self-assigned production role (free text, e.g. "FOH", "PM").
  /// `None` when unset or when received from an older peer (4-arg presence).
  final String? role;
  final DateTime timestamp;

  const PeerPresence({
    required this.peerId,
    required this.peerName,
    required this.channels,
    this.role,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      peerName.hashCode ^
      channels.hashCode ^
      role.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerPresence &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          channels == other.channels &&
          role == other.role &&
          timestamp == other.timestamp;
}

/// Priority levels for PATCH messages.
///
/// Serialized as an integer (0–3) so the Flutter bridge and OSC codec
/// both see a plain number rather than a variant name string.
enum Priority { debug, info, warning, critical }
