// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// A flash/page event targeting a specific channel.
class ChannelFlash {
  final String channelId;
  final UuidValue senderId;
  final String senderName;

  const ChannelFlash({
    required this.channelId,
    required this.senderId,
    required this.senderName,
  });

  @override
  int get hashCode =>
      channelId.hashCode ^ senderId.hashCode ^ senderName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelFlash &&
          runtimeType == other.runtimeType &&
          channelId == other.channelId &&
          senderId == other.senderId &&
          senderName == other.senderName;
}

/// A single PATCH message — maps 1-to-1 to the `/patch/message` OSC packet.
class PatchMessage {
  /// UUID v4 — unique per message, used for ACK and dedup.
  final UuidValue messageId;

  /// Stable UUID for the sender (persisted across sessions).
  final UuidValue senderId;

  /// Human-readable display name for the sender.
  final String senderName;

  /// Stable channel ID (slug, e.g. "rf", "foh").
  final String channelId;

  /// UTC timestamp when the message was created.
  final DateTime timestamp;
  final Priority priority;

  /// The actual message text or shortcut payload.
  final String payload;

  const PatchMessage({
    required this.messageId,
    required this.senderId,
    required this.senderName,
    required this.channelId,
    required this.timestamp,
    required this.priority,
    required this.payload,
  });

  @override
  int get hashCode =>
      messageId.hashCode ^
      senderId.hashCode ^
      senderName.hashCode ^
      channelId.hashCode ^
      timestamp.hashCode ^
      priority.hashCode ^
      payload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PatchMessage &&
          runtimeType == other.runtimeType &&
          messageId == other.messageId &&
          senderId == other.senderId &&
          senderName == other.senderName &&
          channelId == other.channelId &&
          timestamp == other.timestamp &&
          priority == other.priority &&
          payload == other.payload;
}

/// A presence/heartbeat announcement.
class PeerPresence {
  final UuidValue peerId;
  final String peerName;

  /// Which channels this peer is currently subscribed to.
  final List<String> channels;

  /// Optional self-assigned production role (free text, e.g. "FOH", "PM").
  /// `None` when unset or when received from an older peer (4-arg presence).
  final String? role;
  final DateTime timestamp;

  const PeerPresence({
    required this.peerId,
    required this.peerName,
    required this.channels,
    this.role,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      peerName.hashCode ^
      channels.hashCode ^
      role.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerPresence &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          channels == other.channels &&
          role == other.role &&
          timestamp == other.timestamp;
}

/// Priority levels for PATCH messages.
///
/// Serialized as an integer (0–3) so the Flutter bridge and OSC codec
/// both see a plain number rather than a variant name string.
enum Priority { debug, info, warning, critical }
