// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'state/channel.dart';
import 'state/config.dart';
import 'state/peer.dart';
import 'state/session.dart';
import 'transport.dart';
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `csv_escape`, `dispatch_message`, `dispatch_osc`, `init_tracing`, `resolve_peer_names`, `validate_osc`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `engine`

/// Initialize the engine. Idempotent — subsequent calls are no-ops.
///
/// `config_dir`, when `Some`, overrides the platform default data directory
/// (used by tests and by hosts that want to pin the config to a specific path).
Future<void> init({String? configDir}) =>
    RustLib.instance.api.crateApiInit(configDir: configDir);

/// Fire an OSC message to an external target (e.g. QLab). Used by the UI's
/// dual-action macro (the macro sends its Patch message *and* this OSC packet).
Future<void> sendOscMacro({
  required String address,
  required int port,
  required String path,
  String? arg,
}) => RustLib.instance.api.crateApiSendOscMacro(
  address: address,
  port: port,
  path: path,
  arg: arg,
);

/// Sends a message on a channel. Returns the message_id.
Future<String> sendMessage({
  required String channelId,
  required String payload,
  required int priority,
}) => RustLib.instance.api.crateApiSendMessage(
  channelId: channelId,
  payload: payload,
  priority: priority,
);

/// Send a direct (peer-to-peer) message to one peer. Stored locally under a
/// `dm:{peer_id}` key and unicast **only** to that peer (never broadcast/relayed).
/// Returns the message_id. DMs are best-effort (no retransmit) in this version.
Future<String> sendDirectMessage({
  required String peerId,
  required String payload,
  required int priority,
}) => RustLib.instance.api.crateApiSendDirectMessage(
  peerId: peerId,
  payload: payload,
  priority: priority,
);

/// Flashes a channel (sends to peers + fires local event).
Future<void> sendFlash({required String channelId}) =>
    RustLib.instance.api.crateApiSendFlash(channelId: channelId);

/// Announce departure so peers drop us promptly instead of waiting out the
/// heartbeat timeout. Call from the Dart side when the app is closing. Sends a
/// `/patch/bye` directly on the socket (bypassing the queue, so it flushes
/// before the process exits) to every known/static peer plus a LAN broadcast.
/// Best-effort and idempotent — safe to call more than once.
Future<void> shutdown() => RustLib.instance.api.crateApiShutdown();

Future<List<Channel>> getChannels() =>
    RustLib.instance.api.crateApiGetChannels();

Future<List<Peer>> getPeers() => RustLib.instance.api.crateApiGetPeers();

Future<List<PatchMessage>> getMessages({
  required String channelId,
  required int limit,
}) => RustLib.instance.api.crateApiGetMessages(
  channelId: channelId,
  limit: limit,
);

Future<List<InterfaceInfo>> getInterfaces() =>
    RustLib.instance.api.crateApiGetInterfaces();

/// Names of available MIDI input ports (for a future port-selector UI). Empty on
/// platforms without a MIDI backend (iOS/Android) or when no devices are present.
Future<List<String>> getMidiPorts() =>
    RustLib.instance.api.crateApiGetMidiPorts();

Future<ConfigSnapshot> getConfig() => RustLib.instance.api.crateApiGetConfig();

Future<void> setClientName({required String name}) =>
    RustLib.instance.api.crateApiSetClientName(name: name);

/// Set (or clear) the self-assigned role. An empty/whitespace-only string clears
/// it (`None`); otherwise the trimmed value is stored and broadcast in presence.
Future<void> setRole({String? role}) =>
    RustLib.instance.api.crateApiSetRole(role: role);

/// Pass `None` (or an empty string at the caller) to bind all interfaces.
Future<void> setInterface({String? name}) =>
    RustLib.instance.api.crateApiSetInterface(name: name);

Future<void> setFlashOnCritical({required bool enabled}) =>
    RustLib.instance.api.crateApiSetFlashOnCritical(enabled: enabled);

Future<void> setFlashOnMessage({required bool enabled}) =>
    RustLib.instance.api.crateApiSetFlashOnMessage(enabled: enabled);

Future<void> setFlashCount({required int count}) =>
    RustLib.instance.api.crateApiSetFlashCount(count: count);

Future<void> setMacrosColumns({required int columns}) =>
    RustLib.instance.api.crateApiSetMacrosColumns(columns: columns);

Future<void> setHideKeyboard({required bool enabled}) =>
    RustLib.instance.api.crateApiSetHideKeyboard(enabled: enabled);

Future<void> setAudibleAlert({required bool enabled}) =>
    RustLib.instance.api.crateApiSetAudibleAlert(enabled: enabled);

Future<void> setChannelFlash({
  required String channelId,
  bool? flashOnCritical,
  bool? flashOnMessage,
  int? flashCount,
}) => RustLib.instance.api.crateApiSetChannelFlash(
  channelId: channelId,
  flashOnCritical: flashOnCritical,
  flashOnMessage: flashOnMessage,
  flashCount: flashCount,
);

Future<void> addStaticPeer({
  required String address,
  required int port,
  String? label,
}) => RustLib.instance.api.crateApiAddStaticPeer(
  address: address,
  port: port,
  label: label,
);

Future<void> removeStaticPeer({required String address, required int port}) =>
    RustLib.instance.api.crateApiRemoveStaticPeer(address: address, port: port);

/// Remove dynamic (OscBeacon / Mdns) peers not heard from within `max_age_secs`.
/// ManualIp / static peers are never removed.
Future<void> clearStalePeers({required BigInt maxAgeSecs}) =>
    RustLib.instance.api.crateApiClearStalePeers(maxAgeSecs: maxAgeSecs);

Future<void> upsertChannel({
  required String id,
  String? displayName,
  String? color,
}) => RustLib.instance.api.crateApiUpsertChannel(
  id: id,
  displayName: displayName,
  color: color,
);

Future<void> deleteChannel({required String id}) =>
    RustLib.instance.api.crateApiDeleteChannel(id: id);

/// Clear the message buffer for a specific channel, or all channels when `channel_id` is `None`.
Future<void> clearMessages({String? channelId}) =>
    RustLib.instance.api.crateApiClearMessages(channelId: channelId);

/// Export messages to a CSV file at `path`.
/// When `channel_id` is `Some`, only that channel's messages are exported.
/// When `None`, all channels are exported (a `channel` column is included).
Future<void> exportMessages({String? channelId, required String path}) =>
    RustLib.instance.api.crateApiExportMessages(
      channelId: channelId,
      path: path,
    );

Future<void> resetChannels() => RustLib.instance.api.crateApiResetChannels();

/// Ask a peer (by id) for its channel layout. The peer replies with a
/// `/patch/channels/announce`, surfaced to the UI as a `ChannelsOffered` event —
/// it is **not** auto-applied; the UI previews and calls `adopt_channels`.
Future<void> requestChannels({required String peerId}) =>
    RustLib.instance.api.crateApiRequestChannels(peerId: peerId);

/// Adopt channels offered by a peer — **merge** (adds only ids we don't already
/// have; never overwrites or deletes). Returns the number actually added.
Future<int> adoptChannels({required List<Channel> channels}) =>
    RustLib.instance.api.crateApiAdoptChannels(channels: channels);

Future<void> upsertMacro({
  required String channelId,
  required String label,
  required String payload,
  required int priority,
  String? keyBinding,
  int? midiNote,
  int? midiCc,
  OscTarget? osc,
}) => RustLib.instance.api.crateApiUpsertMacro(
  channelId: channelId,
  label: label,
  payload: payload,
  priority: priority,
  keyBinding: keyBinding,
  midiNote: midiNote,
  midiCc: midiCc,
  osc: osc,
);

Future<void> deleteMacro({required String channelId, required String label}) =>
    RustLib.instance.api.crateApiDeleteMacro(
      channelId: channelId,
      label: label,
    );

/// Reorder a channel's macros to match `ordered_labels` (drag-to-reorder).
Future<void> reorderMacros({
  required String channelId,
  required List<String> orderedLabels,
}) => RustLib.instance.api.crateApiReorderMacros(
  channelId: channelId,
  orderedLabels: orderedLabels,
);

Future<void> upsertGlobalMacro({
  required String label,
  required String payload,
  required int priority,
  String? keyBinding,
  int? midiNote,
  int? midiCc,
  OscTarget? osc,
}) => RustLib.instance.api.crateApiUpsertGlobalMacro(
  label: label,
  payload: payload,
  priority: priority,
  keyBinding: keyBinding,
  midiNote: midiNote,
  midiCc: midiCc,
  osc: osc,
);

/// Tell the engine which channels the UI currently has selected, so a
/// MIDI-triggered *global* macro fires on the same channel(s) a tap/F-key would.
/// Includes the reserved `__all__` id when the UI is in ALL/broadcast mode.
Future<void> setSelectedChannels({required List<String> ids}) =>
    RustLib.instance.api.crateApiSetSelectedChannels(ids: ids);

Future<void> deleteGlobalMacro({required String label}) =>
    RustLib.instance.api.crateApiDeleteGlobalMacro(label: label);

/// Restore the factory default global macros (replaces the current set).
Future<void> resetGlobalMacros() =>
    RustLib.instance.api.crateApiResetGlobalMacros();

/// Reorder global macros to match `ordered_labels` (drag-to-reorder).
Future<void> reorderGlobalMacros({required List<String> orderedLabels}) =>
    RustLib.instance.api.crateApiReorderGlobalMacros(
      orderedLabels: orderedLabels,
    );

Future<SessionSaved> saveSession({required String name}) =>
    RustLib.instance.api.crateApiSaveSession(name: name);

/// Export the current channel layout to an arbitrary file path (file-picker).
Future<void> exportLayout({required String path, required String name}) =>
    RustLib.instance.api.crateApiExportLayout(path: path, name: name);

/// Import a session from an arbitrary file path (file-picker) and apply it.
Future<SessionLoaded> importLayout({required String path}) =>
    RustLib.instance.api.crateApiImportLayout(path: path);

Future<SessionLoaded> loadSession({required String slug}) =>
    RustLib.instance.api.crateApiLoadSession(slug: slug);

Future<List<SessionMeta>> listSessions() =>
    RustLib.instance.api.crateApiListSessions();

Future<void> deleteSession({required String slug}) =>
    RustLib.instance.api.crateApiDeleteSession(slug: slug);

/// Subscribe to engine events. Each event is converted to a wire-friendly
/// `PatchAppEvent` and pushed onto the sink. Codegen exposes this in Dart as
/// `Stream<PatchAppEvent> subscribeEvents()`.
///
/// `async` so FRB invokes us with its Tokio runtime as the ambient context —
/// otherwise `tokio::spawn` below has no reactor to attach to.
Stream<PatchAppEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiSubscribeEvents();

/// Lightweight snapshot of the runtime-mutable parts of the config.
/// Mirrors the JSON payload the legacy `get_config` command returned.
class ConfigSnapshot {
  final String clientName;
  final String? role;
  final int oscPort;
  final String? networkInterface;
  final List<StaticPeer> staticPeers;
  final bool flashOnCritical;
  final bool flashOnMessage;
  final int flashCount;
  final int macrosColumns;
  final bool hideKeyboard;
  final bool audibleAlert;
  final List<MacroMessage> globalMacros;

  /// Presence heartbeat interval (seconds). The UI derives its peer
  /// online/amber/grey dot thresholds from this.
  final int heartbeatIntervalSecs;

  const ConfigSnapshot({
    required this.clientName,
    this.role,
    required this.oscPort,
    this.networkInterface,
    required this.staticPeers,
    required this.flashOnCritical,
    required this.flashOnMessage,
    required this.flashCount,
    required this.macrosColumns,
    required this.hideKeyboard,
    required this.audibleAlert,
    required this.globalMacros,
    required this.heartbeatIntervalSecs,
  });

  @override
  int get hashCode =>
      clientName.hashCode ^
      role.hashCode ^
      oscPort.hashCode ^
      networkInterface.hashCode ^
      staticPeers.hashCode ^
      flashOnCritical.hashCode ^
      flashOnMessage.hashCode ^
      flashCount.hashCode ^
      macrosColumns.hashCode ^
      hideKeyboard.hashCode ^
      audibleAlert.hashCode ^
      globalMacros.hashCode ^
      heartbeatIntervalSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigSnapshot &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          role == other.role &&
          oscPort == other.oscPort &&
          networkInterface == other.networkInterface &&
          staticPeers == other.staticPeers &&
          flashOnCritical == other.flashOnCritical &&
          flashOnMessage == other.flashOnMessage &&
          flashCount == other.flashCount &&
          macrosColumns == other.macrosColumns &&
          hideKeyboard == other.hideKeyboard &&
          audibleAlert == other.audibleAlert &&
          globalMacros == other.globalMacros &&
          heartbeatIntervalSecs == other.heartbeatIntervalSecs;
}

@freezed
sealed class PatchAppEvent with _$PatchAppEvent {
  const PatchAppEvent._();

  const factory PatchAppEvent.message(PatchMessage field0) =
      PatchAppEvent_Message;
  const factory PatchAppEvent.messageAcked({
    required String messageId,
    required String peerId,
  }) = PatchAppEvent_MessageAcked;

  /// Delivery progress/result for a critical message we sent.
  const factory PatchAppEvent.messageDelivery({
    required String messageId,
    required int delivered,
    required int total,
    required bool failed,
    required List<String> failedPeers,
  }) = PatchAppEvent_MessageDelivery;
  const factory PatchAppEvent.peerUpdated(PeerPresence field0) =
      PatchAppEvent_PeerUpdated;
  const factory PatchAppEvent.peerExpired({required String peerId}) =
      PatchAppEvent_PeerExpired;
  const factory PatchAppEvent.channelFlash(ChannelFlash field0) =
      PatchAppEvent_ChannelFlash;
  const factory PatchAppEvent.channelListUpdated() =
      PatchAppEvent_ChannelListUpdated;

  /// A peer offered its channel layout (reply to our `request_channels`).
  /// Surfaced for a UI preview/merge prompt — not auto-applied.
  const factory PatchAppEvent.channelsOffered({
    required String fromPeerId,
    required String fromName,
    required List<Channel> channels,
  }) = PatchAppEvent_ChannelsOffered;
  const factory PatchAppEvent.clientNameChanged({required String name}) =
      PatchAppEvent_ClientNameChanged;

  /// The OS denied network access (iOS/macOS Local Network permission).
  const factory PatchAppEvent.permissionDenied({required String context}) =
      PatchAppEvent_PermissionDenied;
}

class SessionLoaded {
  final String slug;
  final String name;
  final int channelCount;

  const SessionLoaded({
    required this.slug,
    required this.name,
    required this.channelCount,
  });

  @override
  int get hashCode => slug.hashCode ^ name.hashCode ^ channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionLoaded &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name &&
          channelCount == other.channelCount;
}

class SessionSaved {
  final String slug;
  final String name;

  const SessionSaved({required this.slug, required this.name});

  @override
  int get hashCode => slug.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSaved &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name;
}
