// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'state/channel.dart';
import 'state/config.dart';
import 'state/peer.dart';
import 'state/show_file.dart';
import 'transport.dart';
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `build_validated_macro`, `forward_decision`, `init_tracing`, `resolve_network_interface`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineHandle`, `EventForward`, `InterfaceResolution`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `engine`

/// Initialize the engine. Idempotent — subsequent calls are no-ops.
///
/// `config_dir`, when `Some`, overrides the platform default data directory
/// (used by tests and by hosts that want to pin the config to a specific path).
Future<void> init({String? configDir}) =>
    RustLib.instance.api.crateApiInit(configDir: configDir);

/// Fire an OSC message to an external target (e.g. QLab). Used by the UI's
/// dual-action macro (the macro sends its Patch message *and* this OSC packet).
/// Validates before touching `engine()` — same pattern as `upsert_macro` — so a
/// bad target returns Err without a running engine; `dispatch_osc` validates
/// again for its other caller (the MIDI fire path), which doesn't go through
/// `engine()` at all.
Future<void> sendOscMacro({
  required String address,
  required int port,
  required String path,
  String? arg,
  required OscArgKind argType,
}) => RustLib.instance.api.crateApiSendOscMacro(
  address: address,
  port: port,
  path: path,
  arg: arg,
  argType: argType,
);

/// Fire a Macro from the UI (tap or F-key): `channel_id` names the Channel a
/// Channel Macro lives on, `None` means a Global Macro. Routing — DM-open
/// precedence, own-channel vs current selection, OSC dual-action exactly once
/// — is owned by `macro_router`, the same brain every other trigger source
/// (MIDI, key binding) goes through. See ADR-0009.
Future<void> fireMacro({String? channelId, required String label}) =>
    RustLib.instance.api.crateApiFireMacro(channelId: channelId, label: label);

/// Fire whatever Macro is bound to key `label`. Precedence is engine-owned:
/// a Channel Macro on a currently-selected Channel beats a Global Macro on
/// the same key; unselected Channels' bindings never fire. Returns whether a
/// macro was bound (the UI consumes the key event only if so).
Future<bool> fireKeyBinding({required String label}) =>
    RustLib.instance.api.crateApiFireKeyBinding(label: label);

/// Sends a message on a channel. Returns the message_id.
Future<String> sendMessage({
  required String channelId,
  required String payload,
  required int priority,
}) => RustLib.instance.api.crateApiSendMessage(
  channelId: channelId,
  payload: payload,
  priority: priority,
);

/// Send a direct (peer-to-peer) message to one peer. Stored locally under a
/// `dm:{peer_id}` key and unicast **only** to that peer (never broadcast/relayed).
/// Returns the message_id. DMs are best-effort (no retransmit) in this version.
Future<String> sendDirectMessage({
  required String peerId,
  required String payload,
  required int priority,
}) => RustLib.instance.api.crateApiSendDirectMessage(
  peerId: peerId,
  payload: payload,
  priority: priority,
);

/// Flashes a channel (sends to peers + fires local event).
Future<void> sendFlash({required String channelId}) =>
    RustLib.instance.api.crateApiSendFlash(channelId: channelId);

/// Send a direct flash/attention ping to one peer. Unicast **only** to that peer
/// (never broadcast); the recipient's DM thread with us flashes. Locally we flash
/// our own `dm:{peer}` thread so the sender sees the ping land too. Best-effort
/// (no ACK/retransmit), mirroring `send_direct_message`.
Future<void> sendDmFlash({required String peerId}) =>
    RustLib.instance.api.crateApiSendDmFlash(peerId: peerId);

/// Announce departure so peers drop us promptly instead of waiting out the
/// heartbeat timeout. Call from the Dart side when the app is closing. Sends a
/// `/patch/bye` directly on the socket (bypassing the queue, so it flushes
/// before the process exits) to every known/static peer plus a LAN broadcast.
/// Best-effort and idempotent — safe to call more than once.
Future<void> shutdown() => RustLib.instance.api.crateApiShutdown();

Future<List<Channel>> getChannels() =>
    RustLib.instance.api.crateApiGetChannels();

Future<List<PeerSnapshot>> getPeers() =>
    RustLib.instance.api.crateApiGetPeers();

Future<List<PatchMessage>> getMessages({
  required String channelId,
  required int limit,
}) => RustLib.instance.api.crateApiGetMessages(
  channelId: channelId,
  limit: limit,
);

Future<List<InterfaceInfo>> getInterfaces() =>
    RustLib.instance.api.crateApiGetInterfaces();

/// Names of available MIDI input ports (for a future port-selector UI). Empty on
/// platforms without a MIDI backend (iOS/Android) or when no devices are present.
Future<List<String>> getMidiPorts() =>
    RustLib.instance.api.crateApiGetMidiPorts();

Future<ConfigSnapshot> getConfig() => RustLib.instance.api.crateApiGetConfig();

Future<void> setClientName({required String name}) =>
    RustLib.instance.api.crateApiSetClientName(name: name);

/// Set (or clear) the self-assigned role. An empty/whitespace-only string clears
/// it (`None`); otherwise the trimmed value is stored and broadcast in presence.
Future<void> setRole({String? role}) =>
    RustLib.instance.api.crateApiSetRole(role: role);

/// Pass `None` (or an empty string at the caller) to bind all interfaces.
Future<void> setInterface({String? name}) =>
    RustLib.instance.api.crateApiSetInterface(name: name);

/// Apply a partial update of the scalar behavior settings — one command for
/// any subset of them, `None` fields untouched (issue #179, ADR-0003-compatible:
/// `AppState` stays the facade, just one deep method instead of seven shallow).
Future<void> patchConfig({required ConfigPatch patch}) =>
    RustLib.instance.api.crateApiPatchConfig(patch: patch);

/// Restore the scalar behavior settings to their factory defaults — the
/// engine owns the default values (issue #180); the UI sends no literals.
Future<void> resetBehaviorConfig() =>
    RustLib.instance.api.crateApiResetBehaviorConfig();

Future<void> setHeartbeatInterval({required BigInt secs}) =>
    RustLib.instance.api.crateApiSetHeartbeatInterval(secs: secs);

/// Change the OSC UDP port and rebind the live socket — no restart. Validated
/// 1024–65535. The socket is rebound **first** (so a bind failure, e.g. the port
/// is already in use, surfaces as an error and leaves the persisted config
/// untouched); only on success is the new port saved.
Future<void> setOscPort({required int port}) =>
    RustLib.instance.api.crateApiSetOscPort(port: port);

Future<void> setChannelFlash({
  required String channelId,
  bool? flashOnCritical,
  bool? flashOnMessage,
  int? flashCount,
}) => RustLib.instance.api.crateApiSetChannelFlash(
  channelId: channelId,
  flashOnCritical: flashOnCritical,
  flashOnMessage: flashOnMessage,
  flashCount: flashCount,
);

Future<void> addStaticPeer({
  required String address,
  required int port,
  String? label,
}) => RustLib.instance.api.crateApiAddStaticPeer(
  address: address,
  port: port,
  label: label,
);

Future<void> removeStaticPeer({required String address, required int port}) =>
    RustLib.instance.api.crateApiRemoveStaticPeer(address: address, port: port);

/// Remove dynamic (OscBeacon / Mdns) peers not heard from within `max_age_secs`.
/// ManualIp / static peers are never removed.
Future<void> clearStalePeers({required BigInt maxAgeSecs}) =>
    RustLib.instance.api.crateApiClearStalePeers(maxAgeSecs: maxAgeSecs);

Future<void> upsertChannel({
  required String id,
  String? displayName,
  String? color,
}) => RustLib.instance.api.crateApiUpsertChannel(
  id: id,
  displayName: displayName,
  color: color,
);

Future<void> deleteChannel({required String id}) =>
    RustLib.instance.api.crateApiDeleteChannel(id: id);

/// Clear the message buffer for a specific channel, or all channels when `channel_id` is `None`.
Future<void> clearMessages({String? channelId}) =>
    RustLib.instance.api.crateApiClearMessages(channelId: channelId);

/// Export messages to a CSV file at `path`.
/// When `channel_id` is `Some`, only that channel's messages are exported.
/// When `None`, all channels are exported (a `channel` column is included).
Future<void> exportMessages({String? channelId, required String path}) =>
    RustLib.instance.api.crateApiExportMessages(
      channelId: channelId,
      path: path,
    );

Future<void> resetChannels() => RustLib.instance.api.crateApiResetChannels();

/// Ask a peer (by id) for its channel layout. The peer replies with a
/// `/patch/channels/announce`, surfaced to the UI as a `ChannelsOffered` event —
/// it is **not** auto-applied; the UI previews and calls `adopt_channels`.
Future<void> requestChannels({required String peerId}) =>
    RustLib.instance.api.crateApiRequestChannels(peerId: peerId);

/// Adopt channels offered by a peer — **merge** (adds only ids we don't already
/// have; never overwrites or deletes). Returns the number actually added.
Future<int> adoptChannels({required List<Channel> channels}) =>
    RustLib.instance.api.crateApiAdoptChannels(channels: channels);

/// Ask a peer (by id) for its global macros. The peer replies with a
/// `/patch/macros/announce`, surfaced to the UI as a `GlobalMacrosOffered`
/// event — it is **not** auto-applied; the UI previews (`preview_global_macros`)
/// and calls `adopt_global_macros`.
Future<void> requestGlobalMacros({required String peerId}) =>
    RustLib.instance.api.crateApiRequestGlobalMacros(peerId: peerId);

/// Classify offered global macros against what this machine already has —
/// for the import preview dialog. Read-only; does not add or persist
/// anything. Each item reports whether it's already had, will be added
/// as-is, will be added with a colliding binding stripped, or will be
/// skipped outright (invalid OSC target).
Future<List<MacroImportOutcome>> previewGlobalMacros({
  required List<MacroMessage> globalMacros,
}) => RustLib.instance.api.crateApiPreviewGlobalMacros(
  globalMacros: globalMacros,
);

/// Adopt global macros offered by a peer — **merge** (adds new macros,
/// strips colliding bindings rather than excluding the macro, drops macros
/// with an invalid OSC target). Returns the same per-item classification as
/// `preview_global_macros` so the UI can report what happened.
Future<List<MacroImportOutcome>> adoptGlobalMacros({
  required List<MacroMessage> globalMacros,
}) =>
    RustLib.instance.api.crateApiAdoptGlobalMacros(globalMacros: globalMacros);

/// Upsert a Macro into either home, keyed on `channel_id` (#186): `Some` is a
/// Channel Macro (stored inside that Channel), `None` is a Global Macro
/// (stored in config, fired on the current selection) — the same
/// discriminator macro routing uses (ADR-0009). The engine-side registries
/// stay split behind this one entry (ADR-0003 lock ownership).
///
/// `original_label` is the macro's label before this edit — pass it when
/// editing an existing macro (even if the label didn't change) so a rename
/// updates that macro in place instead of appending a new one under the new
/// label. Omit (`None`) only when creating a brand-new macro.
Future<void> upsertMacro({
  String? channelId,
  String? originalLabel,
  required String label,
  required String payload,
  required int priority,
  String? keyBinding,
  int? midiNote,
  int? midiCc,
  OscTarget? osc,
}) => RustLib.instance.api.crateApiUpsertMacro(
  channelId: channelId,
  originalLabel: originalLabel,
  label: label,
  payload: payload,
  priority: priority,
  keyBinding: keyBinding,
  midiNote: midiNote,
  midiCc: midiCc,
  osc: osc,
);

Future<void> deleteMacro({required String channelId, required String label}) =>
    RustLib.instance.api.crateApiDeleteMacro(
      channelId: channelId,
      label: label,
    );

/// Reorder a channel's macros to match `ordered_labels` (drag-to-reorder).
Future<void> reorderMacros({
  required String channelId,
  required List<String> orderedLabels,
}) => RustLib.instance.api.crateApiReorderMacros(
  channelId: channelId,
  orderedLabels: orderedLabels,
);

/// Tell the engine which channels the UI currently has selected, so a
/// MIDI-triggered *global* macro fires on the same channel(s) a tap/F-key would.
/// Includes the reserved `__all__` id when the UI is in ALL/broadcast mode.
Future<void> setSelectedChannels({required List<String> ids}) =>
    RustLib.instance.api.crateApiSetSelectedChannels(ids: ids);

/// Tell the engine which peer's DM thread is currently open in the UI (`None`
/// when no DM is open), so a MIDI-triggered macro routes the same way a
/// tap/F-key would — every macro fired while a DM is open goes to that peer
/// instead of a channel (see `_fireMacro` in home_screen.dart).
Future<void> setDmTarget({String? peerId}) =>
    RustLib.instance.api.crateApiSetDmTarget(peerId: peerId);

Future<void> deleteGlobalMacro({required String label}) =>
    RustLib.instance.api.crateApiDeleteGlobalMacro(label: label);

/// Restore the factory default global macros (replaces the current set).
Future<void> resetGlobalMacros() =>
    RustLib.instance.api.crateApiResetGlobalMacros();

/// Reorder global macros to match `ordered_labels` (drag-to-reorder).
Future<void> reorderGlobalMacros({required List<String> orderedLabels}) =>
    RustLib.instance.api.crateApiReorderGlobalMacros(
      orderedLabels: orderedLabels,
    );

Future<ShowFileSaved> saveShowFile({required String name}) =>
    RustLib.instance.api.crateApiSaveShowFile(name: name);

/// Export the current channel layout to an arbitrary file path (file-picker).
Future<void> exportLayout({required String path, required String name}) =>
    RustLib.instance.api.crateApiExportLayout(path: path, name: name);

/// Import a show file from an arbitrary file path (file-picker) and apply it.
Future<ShowFileLoaded> importLayout({required String path}) =>
    RustLib.instance.api.crateApiImportLayout(path: path);

Future<ShowFileLoaded> loadShowFile({required String slug}) =>
    RustLib.instance.api.crateApiLoadShowFile(slug: slug);

Future<List<ShowFileMeta>> listShowFiles() =>
    RustLib.instance.api.crateApiListShowFiles();

Future<void> deleteShowFile({required String slug}) =>
    RustLib.instance.api.crateApiDeleteShowFile(slug: slug);

/// Subscribe to engine events. Each event is converted to a wire-friendly
/// `PatchAppEvent` and pushed onto the sink. Codegen exposes this in Dart as
/// `Stream<PatchAppEvent> subscribeEvents()`.
///
/// `async` so FRB invokes us with its Tokio runtime as the ambient context —
/// otherwise `tokio::spawn` below has no reactor to attach to.
Stream<PatchAppEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiSubscribeEvents();

/// Lightweight snapshot of the runtime-mutable parts of the config.
/// Mirrors the JSON payload the legacy `get_config` command returned.
class ConfigSnapshot {
  final String clientName;
  final String? role;
  final int oscPort;
  final String? networkInterface;
  final List<StaticPeer> staticPeers;
  final bool flashOnCritical;
  final bool flashOnMessage;
  final int flashCount;
  final int macrosColumns;
  final bool hideKeyboard;
  final bool audibleAlert;
  final bool flashWholeScreen;
  final List<MacroMessage> globalMacros;

  /// Presence heartbeat interval (seconds). Editable in Settings; the
  /// online/amber/grey dot thresholds derived from it live engine-side in
  /// `Peer::status` (see `PeerSnapshot`), not in the UI.
  final int heartbeatIntervalSecs;

  /// True while `client_name` is still the system-seeded default — drives the
  /// first-run "set your name" prompt in the UI.
  final bool nameIsDefault;

  const ConfigSnapshot({
    required this.clientName,
    this.role,
    required this.oscPort,
    this.networkInterface,
    required this.staticPeers,
    required this.flashOnCritical,
    required this.flashOnMessage,
    required this.flashCount,
    required this.macrosColumns,
    required this.hideKeyboard,
    required this.audibleAlert,
    required this.flashWholeScreen,
    required this.globalMacros,
    required this.heartbeatIntervalSecs,
    required this.nameIsDefault,
  });

  @override
  int get hashCode =>
      clientName.hashCode ^
      role.hashCode ^
      oscPort.hashCode ^
      networkInterface.hashCode ^
      staticPeers.hashCode ^
      flashOnCritical.hashCode ^
      flashOnMessage.hashCode ^
      flashCount.hashCode ^
      macrosColumns.hashCode ^
      hideKeyboard.hashCode ^
      audibleAlert.hashCode ^
      flashWholeScreen.hashCode ^
      globalMacros.hashCode ^
      heartbeatIntervalSecs.hashCode ^
      nameIsDefault.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigSnapshot &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          role == other.role &&
          oscPort == other.oscPort &&
          networkInterface == other.networkInterface &&
          staticPeers == other.staticPeers &&
          flashOnCritical == other.flashOnCritical &&
          flashOnMessage == other.flashOnMessage &&
          flashCount == other.flashCount &&
          macrosColumns == other.macrosColumns &&
          hideKeyboard == other.hideKeyboard &&
          audibleAlert == other.audibleAlert &&
          flashWholeScreen == other.flashWholeScreen &&
          globalMacros == other.globalMacros &&
          heartbeatIntervalSecs == other.heartbeatIntervalSecs &&
          nameIsDefault == other.nameIsDefault;
}

@freezed
sealed class PatchAppEvent with _$PatchAppEvent {
  const PatchAppEvent._();

  const factory PatchAppEvent.message(PatchMessage field0) =
      PatchAppEvent_Message;
  const factory PatchAppEvent.messageAcked({
    required String messageId,
    required String peerId,
  }) = PatchAppEvent_MessageAcked;

  /// Delivery progress/result for a critical message we sent.
  const factory PatchAppEvent.messageDelivery({
    required String messageId,
    required int delivered,
    required int total,
    required bool failed,
    required List<String> failedPeers,
  }) = PatchAppEvent_MessageDelivery;
  const factory PatchAppEvent.peerUpdated(PeerPresence field0) =
      PatchAppEvent_PeerUpdated;
  const factory PatchAppEvent.peerExpired({required String peerId}) =
      PatchAppEvent_PeerExpired;
  const factory PatchAppEvent.channelFlash(ChannelFlash field0) =
      PatchAppEvent_ChannelFlash;
  const factory PatchAppEvent.channelListUpdated() =
      PatchAppEvent_ChannelListUpdated;

  /// A peer offered its channel layout (reply to our `request_channels`).
  /// Surfaced for a UI preview/merge prompt — not auto-applied.
  const factory PatchAppEvent.channelsOffered({
    required String fromPeerId,
    required String fromName,
    required List<Channel> channels,
  }) = PatchAppEvent_ChannelsOffered;

  /// A peer offered its global macros (reply to our `request_global_macros`).
  /// Surfaced for a UI preview/merge prompt — not auto-applied.
  const factory PatchAppEvent.globalMacrosOffered({
    required String fromPeerId,
    required String fromName,
    required List<MacroMessage> globalMacros,
  }) = PatchAppEvent_GlobalMacrosOffered;
  const factory PatchAppEvent.clientNameChanged({required String name}) =
      PatchAppEvent_ClientNameChanged;

  /// The OS denied network access (iOS/macOS Local Network permission).
  const factory PatchAppEvent.permissionDenied({required String context}) =
      PatchAppEvent_PermissionDenied;

  /// This subscriber's event stream lagged and dropped events — fetched
  /// state (peers, channels, messages) may be stale and must be re-read.
  /// Never converted from an [`AppEvent`]: it's synthesized per-subscriber
  /// in [`subscribe_events`] when *that* receiver falls behind.
  const factory PatchAppEvent.desynced() = PatchAppEvent_Desynced;
}

/// A [`crate::state::peer::Peer`] plus its display [`PeerStatus`] (Online /
/// Stale / Offline), computed against the configured heartbeat interval so
/// the UI never has to re-derive the staleness thresholds itself.
class PeerSnapshot {
  final UuidValue peerId;
  final String peerName;
  final List<String> channels;
  final String? role;
  final DiscoveryMode discoveryMode;
  final String address;
  final int oscPort;
  final DateTime lastSeen;
  final bool departed;
  final PeerStatus status;

  const PeerSnapshot({
    required this.peerId,
    required this.peerName,
    required this.channels,
    this.role,
    required this.discoveryMode,
    required this.address,
    required this.oscPort,
    required this.lastSeen,
    required this.departed,
    required this.status,
  });

  @override
  int get hashCode =>
      peerId.hashCode ^
      peerName.hashCode ^
      channels.hashCode ^
      role.hashCode ^
      discoveryMode.hashCode ^
      address.hashCode ^
      oscPort.hashCode ^
      lastSeen.hashCode ^
      departed.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PeerSnapshot &&
          runtimeType == other.runtimeType &&
          peerId == other.peerId &&
          peerName == other.peerName &&
          channels == other.channels &&
          role == other.role &&
          discoveryMode == other.discoveryMode &&
          address == other.address &&
          oscPort == other.oscPort &&
          lastSeen == other.lastSeen &&
          departed == other.departed &&
          status == other.status;
}

class ShowFileLoaded {
  final String name;
  final int channelCount;

  const ShowFileLoaded({required this.name, required this.channelCount});

  @override
  int get hashCode => name.hashCode ^ channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShowFileLoaded &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          channelCount == other.channelCount;
}

class ShowFileSaved {
  final String slug;
  final String name;

  const ShowFileSaved({required this.slug, required this.name});

  @override
  int get hashCode => slug.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShowFileSaved &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name;
}
