// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'state/channel.dart';
import 'state/config.dart';
import 'state/peer.dart';
import 'state/session.dart';
import 'transport.dart';
part 'api.freezed.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `engine`

/// Initialize the engine. Idempotent — subsequent calls are no-ops.
///
/// `config_dir`, when `Some`, overrides the platform default data directory
/// (used by tests and by hosts that want to pin the config to a specific path).
Future<void> init({String? configDir}) =>
    RustLib.instance.api.crateApiInit(configDir: configDir);

/// Sends a message on a channel. Returns the message_id.
Future<String> sendMessage({
  required String channelId,
  required String payload,
  required int priority,
}) => RustLib.instance.api.crateApiSendMessage(
  channelId: channelId,
  payload: payload,
  priority: priority,
);

/// Flashes a channel (sends to peers + fires local event).
Future<void> sendFlash({required String channelId}) =>
    RustLib.instance.api.crateApiSendFlash(channelId: channelId);

Future<List<Channel>> getChannels() =>
    RustLib.instance.api.crateApiGetChannels();

Future<List<Peer>> getPeers() => RustLib.instance.api.crateApiGetPeers();

Future<List<PatchMessage>> getMessages({
  required String channelId,
  required int limit,
}) => RustLib.instance.api.crateApiGetMessages(
  channelId: channelId,
  limit: limit,
);

Future<List<InterfaceInfo>> getInterfaces() =>
    RustLib.instance.api.crateApiGetInterfaces();

Future<ConfigSnapshot> getConfig() => RustLib.instance.api.crateApiGetConfig();

Future<void> setClientName({required String name}) =>
    RustLib.instance.api.crateApiSetClientName(name: name);

/// Pass `None` (or an empty string at the caller) to bind all interfaces.
Future<void> setInterface({String? name}) =>
    RustLib.instance.api.crateApiSetInterface(name: name);

Future<void> setFlashOnCritical({required bool enabled}) =>
    RustLib.instance.api.crateApiSetFlashOnCritical(enabled: enabled);

Future<void> setFlashOnMessage({required bool enabled}) =>
    RustLib.instance.api.crateApiSetFlashOnMessage(enabled: enabled);

Future<void> setChannelFlash({
  required String channelId,
  bool? flashOnCritical,
  bool? flashOnMessage,
}) => RustLib.instance.api.crateApiSetChannelFlash(
  channelId: channelId,
  flashOnCritical: flashOnCritical,
  flashOnMessage: flashOnMessage,
);

/// NOTE: persistence intentionally not wired here — the legacy bridge
/// command was a no-op too. Tracked under Phase 5 of the FFI migration.
Future<void> addStaticPeer({
  required String address,
  required int port,
  String? label,
}) => RustLib.instance.api.crateApiAddStaticPeer(
  address: address,
  port: port,
  label: label,
);

Future<void> upsertChannel({
  required String id,
  String? displayName,
  String? color,
}) => RustLib.instance.api.crateApiUpsertChannel(
  id: id,
  displayName: displayName,
  color: color,
);

Future<void> deleteChannel({required String id}) =>
    RustLib.instance.api.crateApiDeleteChannel(id: id);

Future<void> upsertShortcut({
  required String channelId,
  required String label,
  required String payload,
  required int priority,
  String? keyBinding,
}) => RustLib.instance.api.crateApiUpsertShortcut(
  channelId: channelId,
  label: label,
  payload: payload,
  priority: priority,
  keyBinding: keyBinding,
);

Future<void> deleteShortcut({
  required String channelId,
  required String label,
}) => RustLib.instance.api.crateApiDeleteShortcut(
  channelId: channelId,
  label: label,
);

Future<SessionSaved> saveSession({required String name}) =>
    RustLib.instance.api.crateApiSaveSession(name: name);

Future<SessionLoaded> loadSession({required String slug}) =>
    RustLib.instance.api.crateApiLoadSession(slug: slug);

Future<List<SessionMeta>> listSessions() =>
    RustLib.instance.api.crateApiListSessions();

Future<void> deleteSession({required String slug}) =>
    RustLib.instance.api.crateApiDeleteSession(slug: slug);

/// Subscribe to engine events. Each event is converted to a wire-friendly
/// `PatchAppEvent` and pushed onto the sink. Codegen exposes this in Dart as
/// `Stream<PatchAppEvent> subscribeEvents()`.
///
/// `async` so FRB invokes us with its Tokio runtime as the ambient context —
/// otherwise `tokio::spawn` below has no reactor to attach to.
Stream<PatchAppEvent> subscribeEvents() =>
    RustLib.instance.api.crateApiSubscribeEvents();

/// Lightweight snapshot of the runtime-mutable parts of the config.
/// Mirrors the JSON payload the legacy `get_config` command returned.
class ConfigSnapshot {
  final String clientName;
  final int oscPort;
  final String? networkInterface;
  final List<StaticPeer> staticPeers;
  final bool flashOnCritical;
  final bool flashOnMessage;

  const ConfigSnapshot({
    required this.clientName,
    required this.oscPort,
    this.networkInterface,
    required this.staticPeers,
    required this.flashOnCritical,
    required this.flashOnMessage,
  });

  @override
  int get hashCode =>
      clientName.hashCode ^
      oscPort.hashCode ^
      networkInterface.hashCode ^
      staticPeers.hashCode ^
      flashOnCritical.hashCode ^
      flashOnMessage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConfigSnapshot &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          oscPort == other.oscPort &&
          networkInterface == other.networkInterface &&
          staticPeers == other.staticPeers &&
          flashOnCritical == other.flashOnCritical &&
          flashOnMessage == other.flashOnMessage;
}

@freezed
sealed class PatchAppEvent with _$PatchAppEvent {
  const PatchAppEvent._();

  const factory PatchAppEvent.message(PatchMessage field0) =
      PatchAppEvent_Message;
  const factory PatchAppEvent.messageAcked({
    required String messageId,
    required String peerId,
  }) = PatchAppEvent_MessageAcked;
  const factory PatchAppEvent.peerUpdated(PeerPresence field0) =
      PatchAppEvent_PeerUpdated;
  const factory PatchAppEvent.peerExpired({required String peerId}) =
      PatchAppEvent_PeerExpired;
  const factory PatchAppEvent.channelFlash(ChannelFlash field0) =
      PatchAppEvent_ChannelFlash;
  const factory PatchAppEvent.channelListUpdated() =
      PatchAppEvent_ChannelListUpdated;
  const factory PatchAppEvent.clientNameChanged({required String name}) =
      PatchAppEvent_ClientNameChanged;
}

class SessionLoaded {
  final String slug;
  final String name;
  final int channelCount;

  const SessionLoaded({
    required this.slug,
    required this.name,
    required this.channelCount,
  });

  @override
  int get hashCode => slug.hashCode ^ name.hashCode ^ channelCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionLoaded &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name &&
          channelCount == other.channelCount;
}

class SessionSaved {
  final String slug;
  final String name;

  const SessionSaved({required this.slug, required this.name});

  @override
  int get hashCode => slug.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SessionSaved &&
          runtimeType == other.runtimeType &&
          slug == other.slug &&
          name == other.name;
}
