// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';
import 'state/channel.dart';
import 'state/config.dart';
import 'state/peer.dart';
import 'state/session.dart';
import 'transport.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  RustStreamSink<PatchAppEvent> dco_decode_StreamSink_patch_app_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChannelFlash dco_decode_box_autoadd_channel_flash(dynamic raw);

  @protected
  OscTarget dco_decode_box_autoadd_osc_target(dynamic raw);

  @protected
  PatchMessage dco_decode_box_autoadd_patch_message(dynamic raw);

  @protected
  PeerPresence dco_decode_box_autoadd_peer_presence(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  Channel dco_decode_channel(dynamic raw);

  @protected
  ChannelFlash dco_decode_channel_flash(dynamic raw);

  @protected
  ConfigSnapshot dco_decode_config_snapshot(dynamic raw);

  @protected
  DiscoveryMode dco_decode_discovery_mode(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  InterfaceInfo dco_decode_interface_info(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Channel> dco_decode_list_channel(dynamic raw);

  @protected
  List<InterfaceInfo> dco_decode_list_interface_info(dynamic raw);

  @protected
  List<MacroMessage> dco_decode_list_macro_message(dynamic raw);

  @protected
  List<PatchMessage> dco_decode_list_patch_message(dynamic raw);

  @protected
  List<Peer> dco_decode_list_peer(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SessionMeta> dco_decode_list_session_meta(dynamic raw);

  @protected
  List<StaticPeer> dco_decode_list_static_peer(dynamic raw);

  @protected
  MacroMessage dco_decode_macro_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  OscTarget? dco_decode_opt_box_autoadd_osc_target(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  OscTarget dco_decode_osc_target(dynamic raw);

  @protected
  PatchAppEvent dco_decode_patch_app_event(dynamic raw);

  @protected
  PatchMessage dco_decode_patch_message(dynamic raw);

  @protected
  Peer dco_decode_peer(dynamic raw);

  @protected
  PeerPresence dco_decode_peer_presence(dynamic raw);

  @protected
  Priority dco_decode_priority(dynamic raw);

  @protected
  SessionLoaded dco_decode_session_loaded(dynamic raw);

  @protected
  SessionMeta dco_decode_session_meta(dynamic raw);

  @protected
  SessionSaved dco_decode_session_saved(dynamic raw);

  @protected
  StaticPeer dco_decode_static_peer(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  RustStreamSink<PatchAppEvent> sse_decode_StreamSink_patch_app_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChannelFlash sse_decode_box_autoadd_channel_flash(
    SseDeserializer deserializer,
  );

  @protected
  OscTarget sse_decode_box_autoadd_osc_target(SseDeserializer deserializer);

  @protected
  PatchMessage sse_decode_box_autoadd_patch_message(
    SseDeserializer deserializer,
  );

  @protected
  PeerPresence sse_decode_box_autoadd_peer_presence(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Channel sse_decode_channel(SseDeserializer deserializer);

  @protected
  ChannelFlash sse_decode_channel_flash(SseDeserializer deserializer);

  @protected
  ConfigSnapshot sse_decode_config_snapshot(SseDeserializer deserializer);

  @protected
  DiscoveryMode sse_decode_discovery_mode(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  InterfaceInfo sse_decode_interface_info(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Channel> sse_decode_list_channel(SseDeserializer deserializer);

  @protected
  List<InterfaceInfo> sse_decode_list_interface_info(
    SseDeserializer deserializer,
  );

  @protected
  List<MacroMessage> sse_decode_list_macro_message(
    SseDeserializer deserializer,
  );

  @protected
  List<PatchMessage> sse_decode_list_patch_message(
    SseDeserializer deserializer,
  );

  @protected
  List<Peer> sse_decode_list_peer(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SessionMeta> sse_decode_list_session_meta(SseDeserializer deserializer);

  @protected
  List<StaticPeer> sse_decode_list_static_peer(SseDeserializer deserializer);

  @protected
  MacroMessage sse_decode_macro_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  OscTarget? sse_decode_opt_box_autoadd_osc_target(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  OscTarget sse_decode_osc_target(SseDeserializer deserializer);

  @protected
  PatchAppEvent sse_decode_patch_app_event(SseDeserializer deserializer);

  @protected
  PatchMessage sse_decode_patch_message(SseDeserializer deserializer);

  @protected
  Peer sse_decode_peer(SseDeserializer deserializer);

  @protected
  PeerPresence sse_decode_peer_presence(SseDeserializer deserializer);

  @protected
  Priority sse_decode_priority(SseDeserializer deserializer);

  @protected
  SessionLoaded sse_decode_session_loaded(SseDeserializer deserializer);

  @protected
  SessionMeta sse_decode_session_meta(SseDeserializer deserializer);

  @protected
  SessionSaved sse_decode_session_saved(SseDeserializer deserializer);

  @protected
  StaticPeer sse_decode_static_peer(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_patch_app_event_Sse(
    RustStreamSink<PatchAppEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_channel_flash(
    ChannelFlash self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_osc_target(
    OscTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_patch_message(
    PatchMessage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_peer_presence(
    PeerPresence self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_channel(Channel self, SseSerializer serializer);

  @protected
  void sse_encode_channel_flash(ChannelFlash self, SseSerializer serializer);

  @protected
  void sse_encode_config_snapshot(
    ConfigSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_discovery_mode(DiscoveryMode self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_interface_info(InterfaceInfo self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_channel(List<Channel> self, SseSerializer serializer);

  @protected
  void sse_encode_list_interface_info(
    List<InterfaceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_macro_message(
    List<MacroMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_patch_message(
    List<PatchMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_peer(List<Peer> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_session_meta(
    List<SessionMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_static_peer(
    List<StaticPeer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_macro_message(MacroMessage self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_osc_target(
    OscTarget? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_osc_target(OscTarget self, SseSerializer serializer);

  @protected
  void sse_encode_patch_app_event(PatchAppEvent self, SseSerializer serializer);

  @protected
  void sse_encode_patch_message(PatchMessage self, SseSerializer serializer);

  @protected
  void sse_encode_peer(Peer self, SseSerializer serializer);

  @protected
  void sse_encode_peer_presence(PeerPresence self, SseSerializer serializer);

  @protected
  void sse_encode_priority(Priority self, SseSerializer serializer);

  @protected
  void sse_encode_session_loaded(SessionLoaded self, SseSerializer serializer);

  @protected
  void sse_encode_session_meta(SessionMeta self, SseSerializer serializer);

  @protected
  void sse_encode_session_saved(SessionSaved self, SseSerializer serializer);

  @protected
  void sse_encode_static_peer(StaticPeer self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
