// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'osc/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'state/channel.dart';
import 'state/config.dart';
import 'state/peer.dart';
import 'state/session.dart';
import 'transport.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 680116124;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'patch_core',
        ioDirectory: '../patch-core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAddStaticPeer({
    required String address,
    required int port,
    String? label,
  });

  Future<void> crateApiDeleteChannel({required String id});

  Future<void> crateApiDeleteMacro({
    required String channelId,
    required String label,
  });

  Future<void> crateApiDeleteSession({required String slug});

  Future<void> crateApiExportLayout({
    required String path,
    required String name,
  });

  Future<List<Channel>> crateApiGetChannels();

  Future<ConfigSnapshot> crateApiGetConfig();

  Future<List<InterfaceInfo>> crateApiGetInterfaces();

  Future<List<PatchMessage>> crateApiGetMessages({
    required String channelId,
    required int limit,
  });

  Future<List<Peer>> crateApiGetPeers();

  Future<SessionLoaded> crateApiImportLayout({required String path});

  Future<void> crateApiInit({String? configDir});

  Future<List<SessionMeta>> crateApiListSessions();

  Future<SessionLoaded> crateApiLoadSession({required String slug});

  Future<void> crateApiRemoveStaticPeer({
    required String address,
    required int port,
  });

  Future<void> crateApiResetChannels();

  Future<SessionSaved> crateApiSaveSession({required String name});

  Future<void> crateApiSendFlash({required String channelId});

  Future<String> crateApiSendMessage({
    required String channelId,
    required String payload,
    required int priority,
  });

  Future<void> crateApiSetChannelFlash({
    required String channelId,
    bool? flashOnCritical,
    bool? flashOnMessage,
    int? flashCount,
  });

  Future<void> crateApiSetClientName({required String name});

  Future<void> crateApiSetFlashCount({required int count});

  Future<void> crateApiSetFlashOnCritical({required bool enabled});

  Future<void> crateApiSetFlashOnMessage({required bool enabled});

  Future<void> crateApiSetHideKeyboard({required bool enabled});

  Future<void> crateApiSetInterface({String? name});

  Future<void> crateApiSetMacrosColumns({required int columns});

  Stream<PatchAppEvent> crateApiSubscribeEvents();

  Future<void> crateApiUpsertChannel({
    required String id,
    String? displayName,
    String? color,
  });

  Future<void> crateApiUpsertMacro({
    required String channelId,
    required String label,
    required String payload,
    required int priority,
    String? keyBinding,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAddStaticPeer({
    required String address,
    required int port,
    String? label,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_opt_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiAddStaticPeerConstMeta,
        argValues: [address, port, label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddStaticPeerConstMeta => const TaskConstMeta(
    debugName: "add_static_peer",
    argNames: ["address", "port", "label"],
  );

  @override
  Future<void> crateApiDeleteChannel({required String id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteChannelConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteChannelConstMeta =>
      const TaskConstMeta(debugName: "delete_channel", argNames: ["id"]);

  @override
  Future<void> crateApiDeleteMacro({
    required String channelId,
    required String label,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          sse_encode_String(label, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteMacroConstMeta,
        argValues: [channelId, label],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteMacroConstMeta => const TaskConstMeta(
    debugName: "delete_macro",
    argNames: ["channelId", "label"],
  );

  @override
  Future<void> crateApiDeleteSession({required String slug}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(slug, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDeleteSessionConstMeta,
        argValues: [slug],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDeleteSessionConstMeta =>
      const TaskConstMeta(debugName: "delete_session", argNames: ["slug"]);

  @override
  Future<void> crateApiExportLayout({
    required String path,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiExportLayoutConstMeta,
        argValues: [path, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportLayoutConstMeta => const TaskConstMeta(
    debugName: "export_layout",
    argNames: ["path", "name"],
  );

  @override
  Future<List<Channel>> crateApiGetChannels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_channel,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetChannelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChannelsConstMeta =>
      const TaskConstMeta(debugName: "get_channels", argNames: []);

  @override
  Future<ConfigSnapshot> crateApiGetConfig() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_config_snapshot,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetConfigConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetConfigConstMeta =>
      const TaskConstMeta(debugName: "get_config", argNames: []);

  @override
  Future<List<InterfaceInfo>> crateApiGetInterfaces() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_interface_info,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiGetInterfacesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetInterfacesConstMeta =>
      const TaskConstMeta(debugName: "get_interfaces", argNames: []);

  @override
  Future<List<PatchMessage>> crateApiGetMessages({
    required String channelId,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_patch_message,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetMessagesConstMeta,
        argValues: [channelId, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMessagesConstMeta => const TaskConstMeta(
    debugName: "get_messages",
    argNames: ["channelId", "limit"],
  );

  @override
  Future<List<Peer>> crateApiGetPeers() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_peer,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetPeersConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetPeersConstMeta =>
      const TaskConstMeta(debugName: "get_peers", argNames: []);

  @override
  Future<SessionLoaded> crateApiImportLayout({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_loaded,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiImportLayoutConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportLayoutConstMeta =>
      const TaskConstMeta(debugName: "import_layout", argNames: ["path"]);

  @override
  Future<void> crateApiInit({String? configDir}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(configDir, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiInitConstMeta,
        argValues: [configDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitConstMeta =>
      const TaskConstMeta(debugName: "init", argNames: ["configDir"]);

  @override
  Future<List<SessionMeta>> crateApiListSessions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_session_meta,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiListSessionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListSessionsConstMeta =>
      const TaskConstMeta(debugName: "list_sessions", argNames: []);

  @override
  Future<SessionLoaded> crateApiLoadSession({required String slug}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(slug, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_loaded,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLoadSessionConstMeta,
        argValues: [slug],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadSessionConstMeta =>
      const TaskConstMeta(debugName: "load_session", argNames: ["slug"]);

  @override
  Future<void> crateApiRemoveStaticPeer({
    required String address,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRemoveStaticPeerConstMeta,
        argValues: [address, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveStaticPeerConstMeta => const TaskConstMeta(
    debugName: "remove_static_peer",
    argNames: ["address", "port"],
  );

  @override
  Future<void> crateApiResetChannels() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiResetChannelsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResetChannelsConstMeta =>
      const TaskConstMeta(debugName: "reset_channels", argNames: []);

  @override
  Future<SessionSaved> crateApiSaveSession({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_session_saved,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSaveSessionConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveSessionConstMeta =>
      const TaskConstMeta(debugName: "save_session", argNames: ["name"]);

  @override
  Future<void> crateApiSendFlash({required String channelId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendFlashConstMeta,
        argValues: [channelId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendFlashConstMeta =>
      const TaskConstMeta(debugName: "send_flash", argNames: ["channelId"]);

  @override
  Future<String> crateApiSendMessage({
    required String channelId,
    required String payload,
    required int priority,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          sse_encode_String(payload, serializer);
          sse_encode_i_32(priority, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSendMessageConstMeta,
        argValues: [channelId, payload, priority],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendMessageConstMeta => const TaskConstMeta(
    debugName: "send_message",
    argNames: ["channelId", "payload", "priority"],
  );

  @override
  Future<void> crateApiSetChannelFlash({
    required String channelId,
    bool? flashOnCritical,
    bool? flashOnMessage,
    int? flashCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          sse_encode_opt_box_autoadd_bool(flashOnCritical, serializer);
          sse_encode_opt_box_autoadd_bool(flashOnMessage, serializer);
          sse_encode_opt_box_autoadd_u_8(flashCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetChannelFlashConstMeta,
        argValues: [channelId, flashOnCritical, flashOnMessage, flashCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetChannelFlashConstMeta => const TaskConstMeta(
    debugName: "set_channel_flash",
    argNames: ["channelId", "flashOnCritical", "flashOnMessage", "flashCount"],
  );

  @override
  Future<void> crateApiSetClientName({required String name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetClientNameConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetClientNameConstMeta =>
      const TaskConstMeta(debugName: "set_client_name", argNames: ["name"]);

  @override
  Future<void> crateApiSetFlashCount({required int count}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(count, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetFlashCountConstMeta,
        argValues: [count],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetFlashCountConstMeta =>
      const TaskConstMeta(debugName: "set_flash_count", argNames: ["count"]);

  @override
  Future<void> crateApiSetFlashOnCritical({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetFlashOnCriticalConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetFlashOnCriticalConstMeta => const TaskConstMeta(
    debugName: "set_flash_on_critical",
    argNames: ["enabled"],
  );

  @override
  Future<void> crateApiSetFlashOnMessage({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetFlashOnMessageConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetFlashOnMessageConstMeta => const TaskConstMeta(
    debugName: "set_flash_on_message",
    argNames: ["enabled"],
  );

  @override
  Future<void> crateApiSetHideKeyboard({required bool enabled}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetHideKeyboardConstMeta,
        argValues: [enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetHideKeyboardConstMeta => const TaskConstMeta(
    debugName: "set_hide_keyboard",
    argNames: ["enabled"],
  );

  @override
  Future<void> crateApiSetInterface({String? name}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetInterfaceConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetInterfaceConstMeta =>
      const TaskConstMeta(debugName: "set_interface", argNames: ["name"]);

  @override
  Future<void> crateApiSetMacrosColumns({required int columns}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(columns, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiSetMacrosColumnsConstMeta,
        argValues: [columns],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetMacrosColumnsConstMeta => const TaskConstMeta(
    debugName: "set_macros_columns",
    argNames: ["columns"],
  );

  @override
  Stream<PatchAppEvent> crateApiSubscribeEvents() {
    final sink = RustStreamSink<PatchAppEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_patch_app_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 28,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiSubscribeEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSubscribeEventsConstMeta =>
      const TaskConstMeta(debugName: "subscribe_events", argNames: ["sink"]);

  @override
  Future<void> crateApiUpsertChannel({
    required String id,
    String? displayName,
    String? color,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(id, serializer);
          sse_encode_opt_String(displayName, serializer);
          sse_encode_opt_String(color, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpsertChannelConstMeta,
        argValues: [id, displayName, color],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpsertChannelConstMeta => const TaskConstMeta(
    debugName: "upsert_channel",
    argNames: ["id", "displayName", "color"],
  );

  @override
  Future<void> crateApiUpsertMacro({
    required String channelId,
    required String label,
    required String payload,
    required int priority,
    String? keyBinding,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(channelId, serializer);
          sse_encode_String(label, serializer);
          sse_encode_String(payload, serializer);
          sse_encode_i_32(priority, serializer);
          sse_encode_opt_String(keyBinding, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiUpsertMacroConstMeta,
        argValues: [channelId, label, payload, priority, keyBinding],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUpsertMacroConstMeta => const TaskConstMeta(
    debugName: "upsert_macro",
    argNames: ["channelId", "label", "payload", "priority", "keyBinding"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<PatchAppEvent> dco_decode_StreamSink_patch_app_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChannelFlash dco_decode_box_autoadd_channel_flash(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_channel_flash(raw);
  }

  @protected
  PatchMessage dco_decode_box_autoadd_patch_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_patch_message(raw);
  }

  @protected
  PeerPresence dco_decode_box_autoadd_peer_presence(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_peer_presence(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Channel dco_decode_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Channel(
      id: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      color: dco_decode_String(arr[2]),
      macros: dco_decode_list_macro_message(arr[3]),
      flashOnCritical: dco_decode_bool(arr[4]),
      flashOnMessage: dco_decode_bool(arr[5]),
      flashCount: dco_decode_opt_box_autoadd_u_8(arr[6]),
    );
  }

  @protected
  ChannelFlash dco_decode_channel_flash(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChannelFlash(
      channelId: dco_decode_String(arr[0]),
      senderId: dco_decode_Uuid(arr[1]),
      senderName: dco_decode_String(arr[2]),
    );
  }

  @protected
  ConfigSnapshot dco_decode_config_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return ConfigSnapshot(
      clientName: dco_decode_String(arr[0]),
      oscPort: dco_decode_u_16(arr[1]),
      networkInterface: dco_decode_opt_String(arr[2]),
      staticPeers: dco_decode_list_static_peer(arr[3]),
      flashOnCritical: dco_decode_bool(arr[4]),
      flashOnMessage: dco_decode_bool(arr[5]),
      flashCount: dco_decode_u_8(arr[6]),
      macrosColumns: dco_decode_u_8(arr[7]),
      hideKeyboard: dco_decode_bool(arr[8]),
    );
  }

  @protected
  DiscoveryMode dco_decode_discovery_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DiscoveryMode.values[raw as int];
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  InterfaceInfo dco_decode_interface_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InterfaceInfo(
      name: dco_decode_String(arr[0]),
      ip: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Channel> dco_decode_list_channel(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_channel).toList();
  }

  @protected
  List<InterfaceInfo> dco_decode_list_interface_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_interface_info).toList();
  }

  @protected
  List<MacroMessage> dco_decode_list_macro_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_macro_message).toList();
  }

  @protected
  List<PatchMessage> dco_decode_list_patch_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_patch_message).toList();
  }

  @protected
  List<Peer> dco_decode_list_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_peer).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SessionMeta> dco_decode_list_session_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_session_meta).toList();
  }

  @protected
  List<StaticPeer> dco_decode_list_static_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_static_peer).toList();
  }

  @protected
  MacroMessage dco_decode_macro_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return MacroMessage(
      label: dco_decode_String(arr[0]),
      payload: dco_decode_String(arr[1]),
      keyBinding: dco_decode_opt_String(arr[2]),
      priority: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bool(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_8(raw);
  }

  @protected
  PatchAppEvent dco_decode_patch_app_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PatchAppEvent_Message(
          dco_decode_box_autoadd_patch_message(raw[1]),
        );
      case 1:
        return PatchAppEvent_MessageAcked(
          messageId: dco_decode_String(raw[1]),
          peerId: dco_decode_String(raw[2]),
        );
      case 2:
        return PatchAppEvent_PeerUpdated(
          dco_decode_box_autoadd_peer_presence(raw[1]),
        );
      case 3:
        return PatchAppEvent_PeerExpired(peerId: dco_decode_String(raw[1]));
      case 4:
        return PatchAppEvent_ChannelFlash(
          dco_decode_box_autoadd_channel_flash(raw[1]),
        );
      case 5:
        return PatchAppEvent_ChannelListUpdated();
      case 6:
        return PatchAppEvent_ClientNameChanged(name: dco_decode_String(raw[1]));
      case 7:
        return PatchAppEvent_PermissionDenied(
          context: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PatchMessage dco_decode_patch_message(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return PatchMessage(
      messageId: dco_decode_Uuid(arr[0]),
      senderId: dco_decode_Uuid(arr[1]),
      senderName: dco_decode_String(arr[2]),
      channelId: dco_decode_String(arr[3]),
      timestamp: dco_decode_Chrono_Utc(arr[4]),
      priority: dco_decode_priority(arr[5]),
      payload: dco_decode_String(arr[6]),
    );
  }

  @protected
  Peer dco_decode_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Peer(
      peerId: dco_decode_Uuid(arr[0]),
      peerName: dco_decode_String(arr[1]),
      channels: dco_decode_list_String(arr[2]),
      discoveryMode: dco_decode_discovery_mode(arr[3]),
      address: dco_decode_String(arr[4]),
      oscPort: dco_decode_u_16(arr[5]),
      lastSeen: dco_decode_Chrono_Utc(arr[6]),
    );
  }

  @protected
  PeerPresence dco_decode_peer_presence(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PeerPresence(
      peerId: dco_decode_Uuid(arr[0]),
      peerName: dco_decode_String(arr[1]),
      channels: dco_decode_list_String(arr[2]),
      timestamp: dco_decode_Chrono_Utc(arr[3]),
    );
  }

  @protected
  Priority dco_decode_priority(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Priority.values[raw as int];
  }

  @protected
  SessionLoaded dco_decode_session_loaded(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SessionLoaded(
      slug: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      channelCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  SessionMeta dco_decode_session_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return SessionMeta(
      slug: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      createdAt: dco_decode_Chrono_Utc(arr[2]),
      channelCount: dco_decode_usize(arr[3]),
    );
  }

  @protected
  SessionSaved dco_decode_session_saved(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SessionSaved(
      slug: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
    );
  }

  @protected
  StaticPeer dco_decode_static_peer(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return StaticPeer(
      address: dco_decode_String(arr[0]),
      port: dco_decode_u_16(arr[1]),
      label: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  RustStreamSink<PatchAppEvent> sse_decode_StreamSink_patch_app_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bool(deserializer));
  }

  @protected
  ChannelFlash sse_decode_box_autoadd_channel_flash(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_channel_flash(deserializer));
  }

  @protected
  PatchMessage sse_decode_box_autoadd_patch_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_patch_message(deserializer));
  }

  @protected
  PeerPresence sse_decode_box_autoadd_peer_presence(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_peer_presence(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_8(deserializer));
  }

  @protected
  Channel sse_decode_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_color = sse_decode_String(deserializer);
    var var_macros = sse_decode_list_macro_message(deserializer);
    var var_flashOnCritical = sse_decode_bool(deserializer);
    var var_flashOnMessage = sse_decode_bool(deserializer);
    var var_flashCount = sse_decode_opt_box_autoadd_u_8(deserializer);
    return Channel(
      id: var_id,
      displayName: var_displayName,
      color: var_color,
      macros: var_macros,
      flashOnCritical: var_flashOnCritical,
      flashOnMessage: var_flashOnMessage,
      flashCount: var_flashCount,
    );
  }

  @protected
  ChannelFlash sse_decode_channel_flash(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_channelId = sse_decode_String(deserializer);
    var var_senderId = sse_decode_Uuid(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    return ChannelFlash(
      channelId: var_channelId,
      senderId: var_senderId,
      senderName: var_senderName,
    );
  }

  @protected
  ConfigSnapshot sse_decode_config_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_clientName = sse_decode_String(deserializer);
    var var_oscPort = sse_decode_u_16(deserializer);
    var var_networkInterface = sse_decode_opt_String(deserializer);
    var var_staticPeers = sse_decode_list_static_peer(deserializer);
    var var_flashOnCritical = sse_decode_bool(deserializer);
    var var_flashOnMessage = sse_decode_bool(deserializer);
    var var_flashCount = sse_decode_u_8(deserializer);
    var var_macrosColumns = sse_decode_u_8(deserializer);
    var var_hideKeyboard = sse_decode_bool(deserializer);
    return ConfigSnapshot(
      clientName: var_clientName,
      oscPort: var_oscPort,
      networkInterface: var_networkInterface,
      staticPeers: var_staticPeers,
      flashOnCritical: var_flashOnCritical,
      flashOnMessage: var_flashOnMessage,
      flashCount: var_flashCount,
      macrosColumns: var_macrosColumns,
      hideKeyboard: var_hideKeyboard,
    );
  }

  @protected
  DiscoveryMode sse_decode_discovery_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DiscoveryMode.values[inner];
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  InterfaceInfo sse_decode_interface_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_ip = sse_decode_String(deserializer);
    return InterfaceInfo(name: var_name, ip: var_ip);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Channel> sse_decode_list_channel(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Channel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_channel(deserializer));
    }
    return ans_;
  }

  @protected
  List<InterfaceInfo> sse_decode_list_interface_info(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <InterfaceInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_interface_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<MacroMessage> sse_decode_list_macro_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MacroMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_macro_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<PatchMessage> sse_decode_list_patch_message(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <PatchMessage>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_patch_message(deserializer));
    }
    return ans_;
  }

  @protected
  List<Peer> sse_decode_list_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Peer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_peer(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SessionMeta> sse_decode_list_session_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SessionMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_session_meta(deserializer));
    }
    return ans_;
  }

  @protected
  List<StaticPeer> sse_decode_list_static_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StaticPeer>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_static_peer(deserializer));
    }
    return ans_;
  }

  @protected
  MacroMessage sse_decode_macro_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_payload = sse_decode_String(deserializer);
    var var_keyBinding = sse_decode_opt_String(deserializer);
    var var_priority = sse_decode_i_32(deserializer);
    return MacroMessage(
      label: var_label,
      payload: var_payload,
      keyBinding: var_keyBinding,
      priority: var_priority,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bool(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_8(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PatchAppEvent sse_decode_patch_app_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_box_autoadd_patch_message(deserializer);
        return PatchAppEvent_Message(var_field0);
      case 1:
        var var_messageId = sse_decode_String(deserializer);
        var var_peerId = sse_decode_String(deserializer);
        return PatchAppEvent_MessageAcked(
          messageId: var_messageId,
          peerId: var_peerId,
        );
      case 2:
        var var_field0 = sse_decode_box_autoadd_peer_presence(deserializer);
        return PatchAppEvent_PeerUpdated(var_field0);
      case 3:
        var var_peerId = sse_decode_String(deserializer);
        return PatchAppEvent_PeerExpired(peerId: var_peerId);
      case 4:
        var var_field0 = sse_decode_box_autoadd_channel_flash(deserializer);
        return PatchAppEvent_ChannelFlash(var_field0);
      case 5:
        return PatchAppEvent_ChannelListUpdated();
      case 6:
        var var_name = sse_decode_String(deserializer);
        return PatchAppEvent_ClientNameChanged(name: var_name);
      case 7:
        var var_context = sse_decode_String(deserializer);
        return PatchAppEvent_PermissionDenied(context: var_context);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PatchMessage sse_decode_patch_message(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_messageId = sse_decode_Uuid(deserializer);
    var var_senderId = sse_decode_Uuid(deserializer);
    var var_senderName = sse_decode_String(deserializer);
    var var_channelId = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_Chrono_Utc(deserializer);
    var var_priority = sse_decode_priority(deserializer);
    var var_payload = sse_decode_String(deserializer);
    return PatchMessage(
      messageId: var_messageId,
      senderId: var_senderId,
      senderName: var_senderName,
      channelId: var_channelId,
      timestamp: var_timestamp,
      priority: var_priority,
      payload: var_payload,
    );
  }

  @protected
  Peer sse_decode_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_Uuid(deserializer);
    var var_peerName = sse_decode_String(deserializer);
    var var_channels = sse_decode_list_String(deserializer);
    var var_discoveryMode = sse_decode_discovery_mode(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_oscPort = sse_decode_u_16(deserializer);
    var var_lastSeen = sse_decode_Chrono_Utc(deserializer);
    return Peer(
      peerId: var_peerId,
      peerName: var_peerName,
      channels: var_channels,
      discoveryMode: var_discoveryMode,
      address: var_address,
      oscPort: var_oscPort,
      lastSeen: var_lastSeen,
    );
  }

  @protected
  PeerPresence sse_decode_peer_presence(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_peerId = sse_decode_Uuid(deserializer);
    var var_peerName = sse_decode_String(deserializer);
    var var_channels = sse_decode_list_String(deserializer);
    var var_timestamp = sse_decode_Chrono_Utc(deserializer);
    return PeerPresence(
      peerId: var_peerId,
      peerName: var_peerName,
      channels: var_channels,
      timestamp: var_timestamp,
    );
  }

  @protected
  Priority sse_decode_priority(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return Priority.values[inner];
  }

  @protected
  SessionLoaded sse_decode_session_loaded(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slug = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channelCount = sse_decode_u_32(deserializer);
    return SessionLoaded(
      slug: var_slug,
      name: var_name,
      channelCount: var_channelCount,
    );
  }

  @protected
  SessionMeta sse_decode_session_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slug = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_Chrono_Utc(deserializer);
    var var_channelCount = sse_decode_usize(deserializer);
    return SessionMeta(
      slug: var_slug,
      name: var_name,
      createdAt: var_createdAt,
      channelCount: var_channelCount,
    );
  }

  @protected
  SessionSaved sse_decode_session_saved(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_slug = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    return SessionSaved(slug: var_slug, name: var_name);
  }

  @protected
  StaticPeer sse_decode_static_peer(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_port = sse_decode_u_16(deserializer);
    var var_label = sse_decode_opt_String(deserializer);
    return StaticPeer(address: var_address, port: var_port, label: var_label);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(
      PlatformInt64Util.from(self.microsecondsSinceEpoch),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_patch_app_event_Sse(
    RustStreamSink<PatchAppEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_patch_app_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_channel_flash(
    ChannelFlash self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_channel_flash(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_patch_message(
    PatchMessage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_patch_message(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_peer_presence(
    PeerPresence self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_peer_presence(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_8(self, serializer);
  }

  @protected
  void sse_encode_channel(Channel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.color, serializer);
    sse_encode_list_macro_message(self.macros, serializer);
    sse_encode_bool(self.flashOnCritical, serializer);
    sse_encode_bool(self.flashOnMessage, serializer);
    sse_encode_opt_box_autoadd_u_8(self.flashCount, serializer);
  }

  @protected
  void sse_encode_channel_flash(ChannelFlash self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.channelId, serializer);
    sse_encode_Uuid(self.senderId, serializer);
    sse_encode_String(self.senderName, serializer);
  }

  @protected
  void sse_encode_config_snapshot(
    ConfigSnapshot self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.clientName, serializer);
    sse_encode_u_16(self.oscPort, serializer);
    sse_encode_opt_String(self.networkInterface, serializer);
    sse_encode_list_static_peer(self.staticPeers, serializer);
    sse_encode_bool(self.flashOnCritical, serializer);
    sse_encode_bool(self.flashOnMessage, serializer);
    sse_encode_u_8(self.flashCount, serializer);
    sse_encode_u_8(self.macrosColumns, serializer);
    sse_encode_bool(self.hideKeyboard, serializer);
  }

  @protected
  void sse_encode_discovery_mode(DiscoveryMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_interface_info(InterfaceInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.ip, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_channel(List<Channel> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_channel(item, serializer);
    }
  }

  @protected
  void sse_encode_list_interface_info(
    List<InterfaceInfo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_interface_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_macro_message(
    List<MacroMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_macro_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_patch_message(
    List<PatchMessage> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_patch_message(item, serializer);
    }
  }

  @protected
  void sse_encode_list_peer(List<Peer> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_session_meta(
    List<SessionMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_session_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_static_peer(
    List<StaticPeer> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_static_peer(item, serializer);
    }
  }

  @protected
  void sse_encode_macro_message(MacroMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.payload, serializer);
    sse_encode_opt_String(self.keyBinding, serializer);
    sse_encode_i_32(self.priority, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bool(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_8(self, serializer);
    }
  }

  @protected
  void sse_encode_patch_app_event(
    PatchAppEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PatchAppEvent_Message(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_patch_message(field0, serializer);
      case PatchAppEvent_MessageAcked(
        messageId: final messageId,
        peerId: final peerId,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_String(messageId, serializer);
        sse_encode_String(peerId, serializer);
      case PatchAppEvent_PeerUpdated(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_box_autoadd_peer_presence(field0, serializer);
      case PatchAppEvent_PeerExpired(peerId: final peerId):
        sse_encode_i_32(3, serializer);
        sse_encode_String(peerId, serializer);
      case PatchAppEvent_ChannelFlash(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_box_autoadd_channel_flash(field0, serializer);
      case PatchAppEvent_ChannelListUpdated():
        sse_encode_i_32(5, serializer);
      case PatchAppEvent_ClientNameChanged(name: final name):
        sse_encode_i_32(6, serializer);
        sse_encode_String(name, serializer);
      case PatchAppEvent_PermissionDenied(context: final context):
        sse_encode_i_32(7, serializer);
        sse_encode_String(context, serializer);
    }
  }

  @protected
  void sse_encode_patch_message(PatchMessage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.messageId, serializer);
    sse_encode_Uuid(self.senderId, serializer);
    sse_encode_String(self.senderName, serializer);
    sse_encode_String(self.channelId, serializer);
    sse_encode_Chrono_Utc(self.timestamp, serializer);
    sse_encode_priority(self.priority, serializer);
    sse_encode_String(self.payload, serializer);
  }

  @protected
  void sse_encode_peer(Peer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.peerId, serializer);
    sse_encode_String(self.peerName, serializer);
    sse_encode_list_String(self.channels, serializer);
    sse_encode_discovery_mode(self.discoveryMode, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.oscPort, serializer);
    sse_encode_Chrono_Utc(self.lastSeen, serializer);
  }

  @protected
  void sse_encode_peer_presence(PeerPresence self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.peerId, serializer);
    sse_encode_String(self.peerName, serializer);
    sse_encode_list_String(self.channels, serializer);
    sse_encode_Chrono_Utc(self.timestamp, serializer);
  }

  @protected
  void sse_encode_priority(Priority self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_session_loaded(SessionLoaded self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slug, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.channelCount, serializer);
  }

  @protected
  void sse_encode_session_meta(SessionMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slug, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_Chrono_Utc(self.createdAt, serializer);
    sse_encode_usize(self.channelCount, serializer);
  }

  @protected
  void sse_encode_session_saved(SessionSaved self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.slug, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_static_peer(StaticPeer self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_16(self.port, serializer);
    sse_encode_opt_String(self.label, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
